### ISSUE TITLE
OpenMP support

### ISSUE THREAD

**Issue by rpep** [conda-forge/fftw-feedstock#20]
Is there a way to install through Conda for a build with OpenMP support? I'm using a project that needs libfftw3_omp.

**Comment by jakirkham** [comment]
It is possible, but does not currently exist. Currently we do support pthreads though.

To support OpenMP, we would probably want to either make that a different package or maybe a feature that one could enable for this package. Personally I'd lean towards a different package because feature support for `conda` is weak and the change to the build seems pretty significant. I say all this for two reasons.

1. We build with pthreads currently.
2. We are building with the system `clang` on Mac.

Thus building support for OpenMP would mean not supporting pthreads FWICT. Also it would mean building with the `gcc` package and/or potentially the `clang` package. Given the nature of these changes, it seems reasonable to separate it somehow from the standard build.

Let's see what others say though.

**Comment by ryanpepper** [comment]
Hi again,

Right, thanks. Thought I was going nuts trying to find it!

It's not the case that you can only build with one or the other - the core functionality is in libfftw3, and the parallel implementations are found in libfftw3_threads and libfftw3_omp. An application has to link libfftw3 and *either* libfftw3_threads or libfftw3_omp however. 

See the following below from [the docs of FFTW](http://www.fftw.org/fftw3_doc/Installation-and-Supported-Hardware_002fSoftware.html#Installation-and-Supported-Hardware_002fSoftware).

I agree that it might be reasonable to separate the build however given the other things you've said. I'll look into creating a new feedstock.

**Comment by fredRos** [comment]
I have the same problem. I'm currently developing the feedstock for [galario](https://github.com/mtazzari/galario/issues/93) and need to link to `libfftw3_omp.so` and `libfftw3f_omp.so`. Getting openmp support across linux and mac seems to be a big pain. 

It would be great to have these `libfftw*_omp.so` libraries built. I can add some keywords that may help. The conda forge `clangdev` and `openmp` packages should deliver a compiler and the openmp runtime from within conda, so one doesn't have to rely on the system libraries.

**Comment by grlee77** [comment]
I would be in favor of just adding OpenMP libs to this existing feedstock since the library names do not conflict.  For example, the system packages for debian/ubuntu include both variants.  It will increase the build time a little, but hopefully it will still be within the CI limits.

I am not certain what the current best practice on conda-forge is for adding OpenMP support on OS X.  In some past recipes I had used `gcc/libgcc` on OS X to get it, but now that the `clangdev` and `openmp` feedstocks exist, perhaps that is a better alternative?

**Comment by fredRos** [comment]
As a workaround, I decided to link to `libfftw_threads.so` etc. in all cases; i.e., no exception in the build process when on conda forge as we had done it for pyfftw.
 I"m not sure about the performance implications but I guess for laptops and desktops there won't be a major difference between openmp and pthreads, yet I didn't find a comparison. I couldn't get my cmake code to recognize the openmp compiler features at build time with `clangdev` so I opted for `gcc/libgcc`. 

@grlee77 can you point to feedstocks where you used this for openmp on mac os? What did you do for openmp on linux? Just assume that `gcc/libgcc` exists?

**Comment by grlee77** [comment]
> @grlee77 can you point to feedstocks where you used this for openmp on mac os? What did you do for openmp on linux? Just assume that gcc/libgcc exists?

Here is an example recipe using OpenMP on both linux and OS X:
https://github.com/conda-forge/nfft-feedstock/blob/master/recipe/meta.yaml

For both linux and OS X, `gcc` is listed in the build requirements and `libgcc` in the run requirements.

**Comment by jakirkham** [comment]
So Anaconda (formerly Continuum) has put together some compilers for Linux and macOS that would be a better fit. Would suggest trying those. Here are the [docs]( https://docs.google.com/document/d/103QY204eD82fJzpT7eXy_rV2bKwe6Hx5uAnkMg_xwkI/edit?usp=sharing ). @msarahan may be able to add more info.

**Comment by rpep** [comment]
The compiler things you mentioned @jakirkham look useful; maybe that's the way to go. I completely forgot about this issue to be honest, although I agree with other suggestions that it's better to have one feedstock for all the libs given that they don't conflict. I've also never seen a pthread vs OpenMP comparison @fredRos, I'd be interested in seeing one though.

**Comment by fredRos** [comment]
A side note: in the master branch of pyfftw, you can now build and pick the threads library. The default is openMP and pthreads the fall back. If you have both libraries and prefer pthreads, set the environment variable `PYFFTW_USE_PTHREADS` before building pyfftw

**Comment by rpep** [comment]
@fredRos Oh, cool! We have some hand wrapped FFTW calls in our C extension for performance reasons, so I need FFTW directly rather than from Python, but I suppose that means we can link against the install of FFTW used in pyfftw without much difficulty.

**Comment by beckermr** [comment]
Hi friends! I have this working for the Anaconda compilers. There is the question of what to do about the toolchain build. I am wondering if we should special case it and not build the openmp libs for it. Any thoughts?

**Comment by steven-murray** [comment]
I just installed this package from conda-forge, and it doesn't have the `libfftwf_omp.so` -- did this get taken out since the above PR was merged? Or am I misunderstanding something?

**Comment by beckermr** [comment]
You are looking for the wrong file. It should be `libfftw3f_omp.so`

**Comment by steven-murray** [comment]
Sorry, I meant that. That file is not in my `anaconda/env/lib/` (no FFTW files with `_omp.so` are there).

**Comment by beckermr** [comment]
Can you send the output of conda-list? The anaconda defaults channel may not have this part of the build.

**Comment by steven-murray** [comment]
[conda-list.txt](https://github.com/conda-forge/fftw-feedstock/files/4540970/conda-list.txt)

Hmmm, maybe it's because I used `conda-forge` rather than default `anaconda` channel?

**Comment by beckermr** [comment]
I don't see fftw in this environment at all. ;p

**Comment by steven-murray** [comment]
I'm so confused... just did `conda install -c conda-forge fftw` on a fresh env and all the `_omp.so` files are there.... not sure why they weren't there the other night when doing (ostensibly) the same thing. Perhaps it was the lateness of the night...

I will get back to you if this problem comes up again and I can determine why. Sorry for the bother! And thanks for packaging this!
