### ISSUE TITLE
No module named 'fftw3'/No module named 'fftw'

### ISSUE THREAD

**Issue by 7yChris** [conda-forge/fftw-feedstock#29]
Hi!Thanks for the share of Fftw packages on conda.
However, I've successfully installed the packages with "conda install -c conda-forge fftw=3.3.6" on mac os and I can find the package installed in anaconda environment. But I just can't import the module with the name fftw3 or fftw, it always tells me that there is no such a module.
I wonder if you know why?
My project deadline is coming soon and this is all I need!! I appreciate it if you can offer me a solution! Thank you!!
<img width="317" alt="2017-06-26 9 37 08" src="https://user-images.githubusercontent.com/26682554/27521773-1daa2400-5a53-11e7-9c29-8eafbd8751ce.png">
<img width="728" alt="2017-06-26 9 37 25" src="https://user-images.githubusercontent.com/26682554/27521774-1ddec408-5a53-11e7-91dc-dbcef1ae5ef3.png">
By the way, the environment is MacOs Sierra 10.12.5, python 3.5.3!

**Comment by jakirkham** [comment]
`fftw` is the C library. So there is no Python part. That said, installing `pyfftw` would install the C library and Python bindings to it if that's what you are looking for.

**Comment by 7yChris** [comment]
Thanks! 
Forgive me because I am very new to python and I am still very confused. 
After I install it in Anaconda, what else should I do so that I can use it in python?

**Comment by grlee77** [comment]
you need to install the pyfftw conda package.  you would then import
pyfftw, not fftw (see their documentation).  If performance is less
critical you can always fall back on the FFT routines in numpy.fft


On Jun 26, 2017 11:29 AM, "7yChris" <notifications@github.com> wrote:

Thanks!
Forgive me because I am very new to python and I am still very confused.
After I install it in Anaconda, what else should I do so that I can use it
in python?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda-forge/fftw-feedstock/issues/29#issuecomment-310955701>,
or mute the thread
