### ISSUE TITLE
No VC14 build

### ISSUE THREAD

**Issue by matmel** [conda-forge/fftw-feedstock#37]
There is no VC14 build of this package for windows listed in conda-forge [files](https://anaconda.org/conda-forge/fftw/files). AFAICT, this causes python 3.6 windows conda package of pyFFTW not to be build.

The [recipe/meta.yaml](https://github.com/conda-forge/fftw-feedstock/blob/master/recipe/meta.yaml) specifies that, on Windows, a conda package should be build with VC14 whereas [appveyor config](https://github.com/conda-forge/fftw-feedstock/blob/master/appveyor.yml) only launches [VC9](https://ci.appveyor.com/project/conda-forge/fftw-feedstock/build/1.0.48/job/v7hgo3g6l9nhfceq#L563).

Is it because a pass of `conda smithy` has been missed?

**Comment by grlee77** [comment]
I haven't looked into the missing FFTW packages here yet, but the main reason there are no windows PyFFTW packages at the moment is because the current PyFFTW release requires single, double and long double precisions to all be present, but we do not build long double FFTW on Windows (I think this was due to VC9 limitations?).

In current master of PyFFTW it is possible to build with only a subset of the precisions present and will be easy to add windows packages for conda-forge once we make a new pyFFTW release (hopefully fairly soon).

**Comment by jakirkham** [comment]
Looks like something went wrong in commit ( https://github.com/conda-forge/fftw-feedstock/commit/ef4b7a32e8db88bbc34e66a0981e06053d290b66 ) and has remained that way since. Bad rerendering maybe.

cc @jschueller

**Comment by grlee77** [comment]
There was also an issue of the library names in the CMAKE-based FFTW build not matching the names PyFFTW is expecting on windows.  That issue was also recently addressed in pyFFTW/pyFFTW#190.

**Comment by jakirkham** [comment]
Think I figured it out. PR ( https://github.com/conda-forge/fftw-feedstock/pull/38 ) should fix the issue.

**Comment by matmel** [comment]
@grlee77, for the `long double` being present in VC14, it doesn't seem like it. [MSDN](https://msdn.microsoft.com/en-us/library/9cx8xs15.aspx) and Numpy [documentation](https://docs.scipy.org/doc/numpy-dev/user/basics.types.html#extended-precision) seem to agree to say that with MSVC, `long double` is mapped to a `double`.

So FFTW built with MSVC (as done on conda-forge) will only have double precision at most. That could be different with mingw I guess.

**Comment by jakirkham** [comment]
Thanks for raising @matmel.

VC14 is back in the build matrix and a new VC14 build has been triggered. May take a little bit to process depending on the queue length.
